// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knstntfjvxzulsfldzuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtuc3RudGZqdnh6dWxzZmxkenVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTg1NzAsImV4cCI6MjA2MjYzNDU3MH0.YPmh4HIDCQJ7m7QlXk2zq6wn2O7JhXXBIBHUyJUBW7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);